import type {
  Asset,
  Incident,
  KbDocument,
  MitreTechnique,
  RawAlert,
  SensorPoint,
  ThreatActor,
} from "./types";

/**
 * ALL DATA IN THIS FILE IS SYNTHETIC AND FICTIONAL.
 * Generated for demonstration/evaluation only. No real operational data.
 */

export const MISSION = {
  id: "MSN-FALCON-SHIELD",
  name: "FALCON SHIELD",
  window: "06:00 – 14:00",
  classificationBanner: "SYNTHETIC DEMONSTRATION DATA — UNCLASSIFIED",
  functions: [
    "Air Surveillance",
    "Air Operations",
    "Ground Mobility",
    "Command & Control",
    "Sustainment",
  ],
};

/** Deterministic pseudo-random so charts are stable between renders/SSR. */
function seeded(seed: number) {
  let s = seed;
  return () => {
    s = (s * 1664525 + 1013904223) % 4294967296;
    return s / 4294967296;
  };
}

function series(
  seed: number,
  base: { temperature: number; vibration: number; pressure: number; rpm: number; fuel: number },
  drift: { temperature: number; vibration: number; pressure: number; rpm: number; fuel: number },
  points = 48,
): SensorPoint[] {
  const rnd = seeded(seed);
  const out: SensorPoint[] = [];
  for (let i = 0; i < points; i++) {
    const p = i / (points - 1);
    const hh = String(Math.floor((i * 30) / 60)).padStart(2, "0");
    const mm = String((i * 30) % 60).padStart(2, "0");
    out.push({
      t: `${hh}:${mm}`,
      temperature: +(base.temperature + drift.temperature * p + (rnd() - 0.5) * 1.6).toFixed(1),
      vibration: +(base.vibration + drift.vibration * p + (rnd() - 0.5) * 0.18).toFixed(2),
      pressure: +(base.pressure + drift.pressure * p + (rnd() - 0.5) * 4).toFixed(0),
      rpm: Math.round(base.rpm + drift.rpm * p + (rnd() - 0.5) * 40),
      fuel: +(base.fuel + drift.fuel * p + (rnd() - 0.5) * 0.6).toFixed(1),
    });
  }
  return out;
}

export const ASSETS: Asset[] = [
  {
    id: "A-17",
    name: "Falcon Aircraft",
    type: "Aircraft",
    location: "Hangar 02",
    health: 72,
    cyberRisk: 21,
    maintenanceRisk: 62,
    criticality: 95,
    operatingHours: 1824,
    flightHours: 1241,
    lastServiceDays: 18,
    nextServiceDays: 12,
    functionName: "Air Operations",
    nominal: { temperature: [68, 82], vibration: [2.0, 3.0], pressure: [175, 205] },
    sensors: series(11, { temperature: 79, vibration: 2.6, pressure: 196, rpm: 2880, fuel: 2.1 }, {
      temperature: 9,
      vibration: 2.1,
      pressure: -34,
      rpm: 60,
      fuel: 6.1,
    }),
    components: [
      {
        name: "Hydraulic Pump",
        failureProbability: 87,
        window: "3–7 days",
        factors: [
          "Hydraulic pressure fluctuation (-17% vs nominal)",
          "Vibration trend 2.6 → 4.7 mm/s over 24h",
          "Engine bay temperature anomaly +8°C",
          "2 prior seal replacements in maintenance history",
          "Matches 14 historical degradation signatures",
        ],
      },
      { name: "Engine Bearing", failureProbability: 71, window: "10–21 days", factors: ["Vibration harmonics", "Operating hours since overhaul"] },
      { name: "Brake Assembly", failureProbability: 34, window: "30–60 days", factors: ["Wear estimate from cycle count"] },
    ],
    serviceHistory: [
      { date: "2026-08-25", action: "Hydraulic seal replacement", technician: "MX-114", notes: "Minor weep at manifold joint." },
      { date: "2026-06-11", action: "100-hr inspection", technician: "MX-091", notes: "All within limits." },
      { date: "2026-03-02", action: "Hydraulic seal replacement", technician: "MX-114", notes: "Recurring wear pattern noted." },
    ],
  },
  {
    id: "A-11",
    name: "Falcon Aircraft",
    type: "Aircraft",
    location: "Hangar 01",
    health: 94,
    cyberRisk: 3,
    maintenanceRisk: 12,
    criticality: 89,
    operatingHours: 902,
    flightHours: 640,
    lastServiceDays: 6,
    nextServiceDays: 44,
    functionName: "Air Operations",
    nominal: { temperature: [68, 82], vibration: [2.0, 3.0], pressure: [175, 205] },
    sensors: series(21, { temperature: 74, vibration: 2.3, pressure: 193, rpm: 2900, fuel: 1.2 }, {
      temperature: 1.5,
      vibration: 0.2,
      pressure: -3,
      rpm: 20,
      fuel: 0.4,
    }),
    components: [
      { name: "Engine Bearing", failureProbability: 42, window: "21–45 days", factors: ["Cycle count", "Minor harmonic drift"] },
      { name: "Avionics Bus", failureProbability: 11, window: ">60 days", factors: ["Nominal"] },
    ],
    serviceHistory: [{ date: "2026-09-06", action: "50-hr inspection", technician: "MX-076", notes: "Nominal." }],
  },
  {
    id: "V-32",
    name: "Armored Vehicle",
    type: "Vehicle",
    location: "Motor Pool B",
    health: 81,
    cyberRisk: 12,
    maintenanceRisk: 55,
    criticality: 82,
    operatingHours: 4210,
    lastServiceDays: 61,
    nextServiceDays: -4,
    functionName: "Ground Mobility",
    nominal: { temperature: [70, 95], vibration: [1.8, 3.2], pressure: [110, 140] },
    sensors: series(31, { temperature: 88, vibration: 2.9, pressure: 128, rpm: 1850, fuel: 3.4 }, {
      temperature: 6,
      vibration: 0.9,
      pressure: -9,
      rpm: -40,
      fuel: 3.2,
    }),
    components: [
      {
        name: "Transmission",
        failureProbability: 69,
        window: "7–14 days",
        factors: ["Shift-pressure irregularity", "Overdue service (+4 days)", "Thermal drift under load"],
      },
      { name: "Cooling Pump", failureProbability: 28, window: "30–60 days", factors: ["Minor flow variance"] },
    ],
    serviceHistory: [{ date: "2026-07-13", action: "Drivetrain service", technician: "MX-203", notes: "Transmission fluid discoloured." }],
  },
  {
    id: "V-18",
    name: "Utility Vehicle",
    type: "Vehicle",
    location: "Motor Pool A",
    health: 91,
    cyberRisk: 6,
    maintenanceRisk: 18,
    criticality: 54,
    operatingHours: 2280,
    lastServiceDays: 14,
    nextServiceDays: 30,
    functionName: "Sustainment",
    nominal: { temperature: [70, 95], vibration: [1.8, 3.2], pressure: [110, 140] },
    sensors: series(41, { temperature: 82, vibration: 2.2, pressure: 126, rpm: 1700, fuel: 1.1 }, {
      temperature: 2,
      vibration: 0.1,
      pressure: -2,
      rpm: 10,
      fuel: 0.3,
    }),
    components: [{ name: "Alternator", failureProbability: 19, window: ">60 days", factors: ["Nominal"] }],
    serviceHistory: [{ date: "2026-08-29", action: "Routine service", technician: "MX-203", notes: "Nominal." }],
  },
  {
    id: "R-04",
    name: "Long Range Radar",
    type: "Radar",
    location: "Sector 04",
    health: 96,
    cyberRisk: 89,
    maintenanceRisk: 9,
    criticality: 98,
    operatingHours: 7640,
    lastServiceDays: 9,
    nextServiceDays: 51,
    functionName: "Air Surveillance",
    nominal: { temperature: [30, 46], vibration: [0.4, 1.2], pressure: [95, 115] },
    sensors: series(51, { temperature: 41, vibration: 0.7, pressure: 106, rpm: 12, fuel: 0 }, {
      temperature: 7,
      vibration: 0.2,
      pressure: -3,
      rpm: 0,
      fuel: 0,
    }),
    components: [
      { name: "Cooling Subsystem", failureProbability: 31, window: "21–45 days", factors: ["Cooling loop temperature drift +7°C"] },
      { name: "Transmit Module", failureProbability: 12, window: ">60 days", factors: ["Nominal"] },
    ],
    serviceHistory: [
      { date: "2026-09-03", action: "Firmware / configuration change", technician: "SYS-018", notes: "Remote management interface re-enabled." },
    ],
  },
  {
    id: "R-07",
    name: "Backup Radar",
    type: "Radar",
    location: "Sector 07",
    health: 93,
    cyberRisk: 8,
    maintenanceRisk: 14,
    criticality: 61,
    operatingHours: 1120,
    lastServiceDays: 21,
    nextServiceDays: 39,
    functionName: "Air Surveillance",
    standby: true,
    nominal: { temperature: [30, 46], vibration: [0.4, 1.2], pressure: [95, 115] },
    sensors: series(61, { temperature: 37, vibration: 0.6, pressure: 104, rpm: 11, fuel: 0 }, {
      temperature: 1,
      vibration: 0.05,
      pressure: -1,
      rpm: 0,
      fuel: 0,
    }),
    components: [{ name: "Transmit Module", failureProbability: 15, window: ">60 days", factors: ["Standby cycling"] }],
    serviceHistory: [{ date: "2026-08-22", action: "Standby readiness check", technician: "SYS-004", notes: "Passed." }],
  },
  {
    id: "C-12",
    name: "Communication Node",
    type: "Communication",
    location: "Relay Site C",
    health: 89,
    cyberRisk: 24,
    maintenanceRisk: 11,
    criticality: 94,
    operatingHours: 9010,
    lastServiceDays: 12,
    nextServiceDays: 48,
    functionName: "Command & Control",
    nominal: { temperature: [28, 44], vibration: [0.2, 0.9], pressure: [90, 110] },
    sensors: series(71, { temperature: 39, vibration: 0.5, pressure: 101, rpm: 0, fuel: 0 }, {
      temperature: 3,
      vibration: 0.1,
      pressure: -2,
      rpm: 0,
      fuel: 0,
    }),
    components: [{ name: "Uplink Amplifier", failureProbability: 22, window: "30–60 days", factors: ["Thermal cycling"] }],
    serviceHistory: [{ date: "2026-08-31", action: "Antenna alignment", technician: "SYS-011", notes: "Nominal." }],
  },
  {
    id: "P-03",
    name: "Field Power System",
    type: "Power System",
    location: "Sector 04",
    health: 87,
    cyberRisk: 10,
    maintenanceRisk: 26,
    criticality: 76,
    operatingHours: 5330,
    lastServiceDays: 33,
    nextServiceDays: 9,
    functionName: "Sustainment",
    nominal: { temperature: [50, 78], vibration: [1.0, 2.4], pressure: [80, 100] },
    sensors: series(81, { temperature: 71, vibration: 1.9, pressure: 92, rpm: 1500, fuel: 4.2 }, {
      temperature: 4,
      vibration: 0.3,
      pressure: -3,
      rpm: -15,
      fuel: 1.1,
    }),
    components: [{ name: "Generator Coupling", failureProbability: 37, window: "14–30 days", factors: ["Vibration trend", "Service due in 9 days"] }],
    serviceHistory: [{ date: "2026-08-10", action: "Load bank test", technician: "MX-160", notes: "Within limits." }],
  },
  {
    id: "F-08",
    name: "Bulk Fuel System",
    type: "Fuel System",
    location: "Depot 1",
    health: 92,
    cyberRisk: 7,
    maintenanceRisk: 15,
    criticality: 68,
    operatingHours: 6120,
    lastServiceDays: 25,
    nextServiceDays: 35,
    functionName: "Sustainment",
    nominal: { temperature: [15, 35], vibration: [0.3, 1.0], pressure: [60, 85] },
    sensors: series(91, { temperature: 27, vibration: 0.6, pressure: 74, rpm: 900, fuel: 0.8 }, {
      temperature: 1,
      vibration: 0.05,
      pressure: -1,
      rpm: 5,
      fuel: 0.2,
    }),
    components: [{ name: "Transfer Pump", failureProbability: 17, window: ">60 days", factors: ["Nominal"] }],
    serviceHistory: [{ date: "2026-08-18", action: "Filtration service", technician: "MX-140", notes: "Nominal." }],
  },
];

export const RAW_ALERTS: RawAlert[] = [
  {
    id: "ALT-8841",
    ts: "10:01:07",
    assetId: "R-04",
    user: "svc_radarops",
    srcIp: "198.51.100.42",
    dstIp: "10.20.4.14",
    process: "winlogon.exe",
    eventType: "Authentication Failure",
    technique: "T1078",
    severity: "MEDIUM",
    description: "6 failed authentication attempts against radar management interface.",
  },
  {
    id: "ALT-8846",
    ts: "10:04:22",
    assetId: "R-04",
    user: "svc_radarops",
    srcIp: "198.51.100.42",
    dstIp: "10.20.4.14",
    process: "winlogon.exe",
    eventType: "Unusual Successful Login",
    technique: "T1078",
    severity: "HIGH",
    description: "Successful login from atypical source range outside maintenance window.",
    ioc: "198.51.100.42",
  },
  {
    id: "ALT-8851",
    ts: "10:06:40",
    assetId: "R-04",
    user: "svc_radarops",
    srcIp: "10.20.4.14",
    dstIp: "10.20.4.14",
    process: "powershell.exe",
    eventType: "Encoded PowerShell Execution",
    technique: "T1059.001",
    severity: "HIGH",
    description: "Base64-encoded command line executed by service account.",
  },
  {
    id: "ALT-8859",
    ts: "10:08:55",
    assetId: "R-04",
    user: "svc_radarops",
    srcIp: "10.20.4.14",
    dstIp: "10.20.4.14",
    process: "lsass.exe",
    eventType: "Credential Access Indicator",
    technique: "T1003",
    severity: "CRITICAL",
    description: "Anomalous handle request against credential store process.",
  },
  {
    id: "ALT-8864",
    ts: "10:11:19",
    assetId: "R-04",
    user: "svc_radarops",
    srcIp: "10.20.4.14",
    dstIp: "203.0.113.77",
    process: "powershell.exe",
    eventType: "Suspicious Outbound Connection",
    technique: "T1071.001",
    severity: "HIGH",
    description: "Beacon-like outbound HTTPS to low-reputation infrastructure.",
    ioc: "203.0.113.77",
  },
  {
    id: "ALT-8872",
    ts: "11:22:04",
    assetId: "C-12",
    user: "op_kestrel",
    srcIp: "10.20.7.31",
    dstIp: "203.0.113.77",
    process: "curl.exe",
    eventType: "Suspicious Outbound Connection",
    technique: "T1071.001",
    severity: "HIGH",
    description: "Outbound connection to infrastructure shared with R-04 activity.",
    ioc: "203.0.113.77",
  },
  {
    id: "ALT-8875",
    ts: "11:24:41",
    assetId: "C-12",
    user: "op_kestrel",
    srcIp: "10.20.7.31",
    dstIp: "10.20.7.1",
    process: "net.exe",
    eventType: "Network Share Discovery",
    technique: "T1135",
    severity: "MEDIUM",
    description: "Enumeration of adjacent network shares from relay node.",
  },
  {
    id: "ALT-8881",
    ts: "12:02:16",
    assetId: "V-32",
    user: "mx_diagnostic",
    srcIp: "10.20.9.55",
    dstIp: "10.20.9.10",
    process: "diagtool.exe",
    eventType: "Unsigned Binary Execution",
    technique: "T1204",
    severity: "MEDIUM",
    description: "Unsigned diagnostic tool executed on maintenance terminal.",
  },
  {
    id: "ALT-8890",
    ts: "12:41:03",
    assetId: "P-03",
    user: "svc_power",
    srcIp: "10.20.3.8",
    dstIp: "10.20.3.1",
    process: "scada.exe",
    eventType: "Configuration Change",
    technique: "T1562",
    severity: "LOW",
    description: "Telemetry logging level reduced on power controller.",
  },
];

export const INCIDENTS: Incident[] = [
  {
    id: "INC-042",
    title: "Potential Credential Compromise",
    assetId: "R-04",
    severity: "CRITICAL",
    alertIds: ["ALT-8841", "ALT-8846", "ALT-8851", "ALT-8859", "ALT-8864"],
    threatScore: 91,
    confidence: 91,
    correlationBasis: [
      "Same asset (R-04)",
      "Same account (svc_radarops)",
      "11-minute event window",
      "Related ATT&CK techniques (T1078 → T1059.001 → T1003)",
      "IOC match on outbound destination",
    ],
    chain: {
      "Initial Access": "confirmed",
      "Credential Access": "confirmed",
      Execution: "confirmed",
      Persistence: "suspected",
      Discovery: "suspected",
      "Lateral Movement": "suspected",
      "Command & Control": "confirmed",
      Impact: "none",
    },
    actor: "APT-X7",
    status: "OPEN",
  },
  {
    id: "INC-047",
    title: "Suspicious Outbound Activity on Relay Node",
    assetId: "C-12",
    severity: "HIGH",
    alertIds: ["ALT-8872", "ALT-8875"],
    threatScore: 74,
    confidence: 78,
    correlationBasis: ["Same asset (C-12)", "Shared destination IOC with INC-042", "3-minute event window"],
    chain: {
      "Initial Access": "suspected",
      "Credential Access": "none",
      Execution: "none",
      Persistence: "none",
      Discovery: "confirmed",
      "Lateral Movement": "suspected",
      "Command & Control": "confirmed",
      Impact: "none",
    },
    actor: "APT-X7",
    status: "MONITORING",
  },
  {
    id: "INC-051",
    title: "Unsigned Tooling on Maintenance Terminal",
    assetId: "V-32",
    severity: "MEDIUM",
    alertIds: ["ALT-8881"],
    threatScore: 41,
    confidence: 62,
    correlationBasis: ["Single asset (V-32)", "No supporting intelligence match"],
    chain: {
      "Initial Access": "none",
      "Credential Access": "none",
      Execution: "confirmed",
      Persistence: "none",
      Discovery: "none",
      "Lateral Movement": "none",
      "Command & Control": "none",
      Impact: "none",
    },
    status: "MONITORING",
  },
  {
    id: "INC-055",
    title: "Telemetry Logging Reduced on Power Controller",
    assetId: "P-03",
    severity: "LOW",
    alertIds: ["ALT-8890"],
    threatScore: 28,
    confidence: 54,
    correlationBasis: ["Single configuration event", "Change ticket not yet verified"],
    chain: {
      "Initial Access": "none",
      "Credential Access": "none",
      Execution: "none",
      Persistence: "none",
      Discovery: "none",
      "Lateral Movement": "none",
      "Command & Control": "none",
      Impact: "none",
    },
    status: "MONITORING",
  },
];

export const THREAT_ACTORS: ThreatActor[] = [
  {
    id: "TA-01",
    name: "APT-X7",
    confidence: 87,
    techniques: ["T1078", "T1059.001", "T1003", "T1071.001"],
    affectedAssets: ["R-04", "C-12"],
    level: "CRITICAL",
    summary:
      "Fictional actor profile modelled on credential-abuse tradecraft against sensor and relay infrastructure. Indicators suggest reconnaissance followed by valid-account misuse.",
    iocs: [
      { type: "IPv4", value: "203.0.113.77", confidence: 92 },
      { type: "IPv4", value: "198.51.100.42", confidence: 84 },
      { type: "Domain", value: "update-node.example", confidence: 71 },
    ],
  },
  {
    id: "TA-02",
    name: "GRAYFINCH",
    confidence: 64,
    techniques: ["T1566", "T1204"],
    affectedAssets: ["V-32"],
    level: "MEDIUM",
    summary: "Opportunistic tooling delivery against maintenance workstations. Low confidence attribution.",
    iocs: [{ type: "SHA256", value: "3f9a…c771", confidence: 58 }],
  },
  {
    id: "TA-03",
    name: "SABLE DRIFT",
    confidence: 49,
    techniques: ["T1562", "T1135"],
    affectedAssets: ["P-03"],
    level: "LOW",
    summary: "Defence-evasion patterns observed in sector telemetry. Insufficient corroboration for attribution.",
    iocs: [{ type: "Domain", value: "cfg-sync.example", confidence: 44 }],
  },
];

export const MITRE: MitreTechnique[] = [
  { id: "T1078", name: "Valid Accounts", tactic: "Initial Access", evidence: "Successful login from atypical range using svc_radarops after 6 failures.", confidence: 88 },
  { id: "T1059.001", name: "PowerShell", tactic: "Execution", evidence: "Base64-encoded command line executed 2 minutes after login.", confidence: 84 },
  { id: "T1003", name: "OS Credential Dumping", tactic: "Credential Access", evidence: "Anomalous handle request against credential store process.", confidence: 79 },
  { id: "T1071.001", name: "Application Layer Protocol: Web", tactic: "Command & Control", evidence: "Beacon-like outbound HTTPS to low-reputation host 203.0.113.77.", confidence: 82 },
  { id: "T1135", name: "Network Share Discovery", tactic: "Discovery", evidence: "Share enumeration from relay node C-12.", confidence: 66 },
  { id: "T1204", name: "User Execution", tactic: "Execution", evidence: "Unsigned diagnostic binary launched by maintenance account.", confidence: 61 },
  { id: "T1562", name: "Impair Defenses", tactic: "Defense Evasion", evidence: "Telemetry logging level reduced on P-03.", confidence: 52 },
];

export const KB_DOCUMENTS: KbDocument[] = [
  { id: "DOC-001", title: "Aircraft A-17 Maintenance Manual", type: "Maintenance Manual", section: "Hydraulic System", updated: "2026-08-30", assetId: "A-17", snippet: "Hydraulic pump degradation typically presents as pressure fluctuation greater than 12% below nominal combined with rising drive-end vibration." },
  { id: "DOC-002", title: "A-17 Service Record Log", type: "Service Record", section: "Seal Replacement History", updated: "2026-08-25", assetId: "A-17", snippet: "Two hydraulic seal replacements recorded within six months; recurrence indicates upstream pump wear." },
  { id: "DOC-003", title: "Radar R-04 Asset Specification", type: "Asset Specification", section: "Remote Management Interface", updated: "2026-09-03", assetId: "R-04", snippet: "Remote management interface is restricted to the maintenance VLAN during scheduled windows only." },
  { id: "DOC-004", title: "Incident Response SOP", type: "SOP", section: "Credential Compromise Playbook", updated: "2026-07-19", snippet: "On suspected credential compromise: validate account, review endpoint telemetry, inspect outbound sessions, assess lateral movement, escalate to duty officer." },
  { id: "DOC-005", title: "Threat Report: APT-X7 Tradecraft", type: "Threat Report", section: "Valid Account Abuse", updated: "2026-09-08", snippet: "Fictional actor profile: prefers service-account abuse and encoded PowerShell staging before web-protocol C2." },
  { id: "DOC-006", title: "Falcon Shield Mission Order (Extract)", type: "Intelligence Report", section: "Surveillance Dependencies", updated: "2026-09-10", snippet: "Air surveillance coverage for the mission window depends on R-04 primary with R-07 designated standby." },
  { id: "DOC-007", title: "Vehicle V-32 Maintenance Manual", type: "Maintenance Manual", section: "Transmission", updated: "2026-07-13", assetId: "V-32", snippet: "Shift-pressure irregularity under thermal load is an early transmission wear indicator." },
];

export const KB_STATS = { documents: 127, indexed: 127, lastUpdated: "2 minutes ago" };

export const ALERT_FUNNEL = [
  { stage: "Raw Alerts", value: 2847, note: "SIEM + EDR + network sensors" },
  { stage: "After Deduplication", value: 1943, note: "Identical signatures collapsed" },
  { stage: "Correlated Events", value: 421, note: "Entity + time-window grouping" },
  { stage: "Potential Incidents", value: 37, note: "Context analysis applied" },
  { stage: "Critical Incidents", value: 4, note: "Mission-weighted prioritisation" },
];

export const DEPENDENCIES = [
  { group: "Aircraft", ready: 8, total: 10 },
  { group: "Vehicles", ready: 14, total: 15 },
  { group: "Radar", ready: 3, total: 4 },
  { group: "Communication", ready: 5, total: 5 },
  { group: "Logistics", ready: 9, total: 10 },
];

export function getAsset(id: string) {
  return ASSETS.find((a) => a.id === id);
}
export function getIncident(id: string) {
  return INCIDENTS.find((i) => i.id === id);
}
export function getAlert(id: string) {
  return RAW_ALERTS.find((a) => a.id === id);
}
